# Generated by Django 3.2.13 on 2022-09-10 17:02

import Recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=50, validators=[Recipes.validators.unit_validator]),
        ),
    ]
